/* Run against an isolated server at QCT_TEST_URL; production demo data is never modified. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({ channel:'msedge', headless:true });
  const base = process.env.QCT_TEST_URL || 'http://127.0.0.1:8767';
  const context = await browser.newContext({ viewport:{width:1440,height:1050}, deviceScaleFactor:1 });
  const page = await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const out=path.resolve('artifacts/screenshots');fs.mkdirSync(out,{recursive:true});
  try{
    await page.goto(base);await page.getByRole('heading',{name:'企业政策工作台'}).waitFor();
    await page.screenshot({path:path.join(out,'01-dashboard.png'),fullPage:true});
    await page.getByRole('button',{name:'开始一次预审'}).click();
    await page.locator('#as-of').fill('2026-09-22');await page.locator('#as-of').dispatchEvent('change');
    await page.getByRole('button',{name:'执行预审'}).click();
    await page.getByRole('heading',{name:'已核对条件满足',exact:true}).waitFor();
    await page.getByRole('button',{name:/近三年研发费用比例/}).click();
    assert((await page.locator('#main').innerText()).includes('6.84%'));
    await page.screenshot({path:path.join(out,'02-review.png'),fullPage:true});
    const downloadWait=page.waitForEvent('download');await page.getByRole('link',{name:'导出报告'}).click();
    const downloaded=await downloadWait;assert(downloaded.suggestedFilename().endsWith('.md'));
    await page.locator('#company-select').selectOption('demo-02');
    await page.getByRole('button',{name:'执行预审'}).click();
    await page.getByRole('heading',{name:'待补证或复核',exact:true}).waitFor();
    await page.getByRole('link',{name:'政策与材料',exact:true}).click();
    await page.locator('#asset-file').setInputFiles({name:'2024研发费用补证.csv',mimeType:'text/csv',buffer:Buffer.from('字段,数值,单位,期间\nrd_2024,220,万元,2024\n')});
    await page.locator('#proposal-company').waitFor();
    await page.locator('#proposal-company').selectOption('demo-02');
    await page.getByRole('button',{name:'确认候选',exact:true}).click();
    await page.locator('#dialog .badge.pass').filter({hasText:'已确认'}).waitFor();
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    await page.getByRole('link',{name:'企业预审',exact:true}).click();
    await page.getByRole('button',{name:'执行预审'}).click();
    await page.getByRole('heading',{name:'已核对条件满足',exact:true}).waitFor();
    await page.locator('#policy-select').selectOption('sme-bj-2026');
    await page.getByRole('button',{name:'执行预审'}).click();
    await page.getByText('受理窗口：本年度填报已截止',{exact:false}).waitFor();
    await page.getByRole('link',{name:'版本演进',exact:true}).click();
    await page.getByRole('heading',{name:'2026 科技型中小企业评价'}).waitFor();
    assert((await page.locator('#main').innerText()).includes('2026-08-31'));
    await page.screenshot({path:path.join(out,'03-version-evolution.png'),fullPage:true});
    await page.getByRole('link',{name:'知识关联',exact:true}).click();
    await page.locator('.graph-svg').waitFor();
    await page.screenshot({path:path.join(out,'04-evidence-graph.png'),fullPage:true});
    await page.getByRole('link',{name:'政策与材料',exact:true}).click();
    await page.locator('#search-q').fill('研发费用');await page.getByRole('button',{name:'检索',exact:true}).click();
    await page.locator('.search-result').first().waitFor();
    await page.locator('#upload-purpose').selectOption('policy');
    await page.locator('#asset-file').setInputFiles({name:'领域概念.txt',mimeType:'text/plain',buffer:Buffer.from('研发费用和销售收入需要按会计年度归集。')});
    await page.getByRole('button',{name:'确认候选',exact:true}).first().waitFor();
    await page.getByRole('button',{name:'确认候选',exact:true}).first().click();
    await page.locator('#dialog .badge.pass').filter({hasText:'已确认'}).first().waitFor();
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    await page.locator('#upload-purpose').selectOption('policy');
    await page.locator('#asset-file').setInputFiles({name:'阈值假设.txt',mimeType:'text/plain',buffer:Buffer.from('职工总数不超过50人。')});
    await page.getByRole('button',{name:'提取候选并预览影响'}).click();
    await page.locator('#change-preview .evidence-card').first().waitFor();
    assert((await page.locator('#change-preview').innerText()).includes('500 → 50 人'));
    await page.screenshot({path:path.join(out,'07-policy-change-preview.png'),fullPage:true});
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    await page.getByRole('link',{name:'运行记录',exact:true}).click();
    await page.getByRole('heading',{name:'已保存的预审报告'}).waitFor();
    await page.getByRole('link',{name:'评测中心',exact:true}).click();
    await page.getByRole('heading',{name:'评测中心',exact:true}).waitFor();
    await page.getByRole('heading',{name:'逐案例结果',exact:true}).waitFor();
    assert((await page.locator('#main').innerText()).includes('100.0%'));
    await page.screenshot({path:path.join(out,'05-evaluation.png'),fullPage:true});
    await page.getByRole('link',{name:'工作台',exact:true}).click();
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('heading',{name:'企业政策工作台'}).waitFor();
    await page.locator('#toast').waitFor({state:'hidden'});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
    await page.screenshot({path:path.join(out,'06-mobile.png'),fullPage:true});
    assert.deepEqual(errors,[]);
    const result={passed:true,flows:['首页','完整预审与证据展开','Markdown 导出','缺失材料预审','上传补证与确认','补证后重新预审','窗口关闭与条件分离','版本比较','证据图','来源检索','概念确认','政策变化候选与影响预览','操作历史','困难案例评测中心','移动端布局'],console_errors:errors,at:new Date().toISOString()};
    fs.writeFileSync('artifacts/browser-results.json',JSON.stringify(result,null,2));
    console.log(JSON.stringify(result));
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
